version: '3.6'
services:
  front:
    image: {your-docker-image-name}:latest
    restart: always
    environment:
      - VIRTUAL_HOST={your-host-name(url)}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST={your-host-name(url)}
      - LETSENCRYPT_EMAIL={your-email}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy
